### PR TITLE
Fix timeout in PollTCPPort

### PR DESCRIPTION
**Pull request by oskaritimperi**
Use both `tv_sec` and `tv_usec` fields of `struct timeval` for specifying the timeout.

### CODE REVIEW

**Comment by oskaritimperi** [comment]
@TeroK should this merge request be going to develop rather than master?

**Review by TeroK — COMMENTED** [review]
Thanks! It's a good find and seems to fix a real problem. Will make this in develop branch now.

**Review by TeroK — APPROVED** [review]

**Comment by oskaritimperi** [comment]
OK. This was committed to develop outside of the PR. I'm closing this as the actual code is in develop branch.

**Comment by TeroK** [comment]
Yes, I somehow messed the PR and ended up copying the modifications manually.

**Pull request closed without merging**
