### PR TITLE
Add description funcs

### PR DESCRIPTION
**Pull request by koivunej**
Add description functions that behave a bit like `snprintf`:
 * `smDescribeSmStatus(char*, size_t, SM_STATUS)`
 * `smDescribeStatus(char*, size_t, int32_t)`
 * `smDescribeFault(char*, size_t, int32_t)`

Probably good to roll up as one commit.

### CODE REVIEW

**Comment by koivunej** [comment]
windows build broken at least for other reasons (unistd.h), gcc + clang fail due to (sanitizer) and static linking.

**Comment by koivunej** [comment]
windows build broken for some return code 0x2:

```
devicedeployment.c(3): fatal error C1083: Cannot open include file: 'crc.h': No such file or directory
```

otherwise good. the first windows issue was stray `unistd.h` include (fixed with `stdint.h`) but this is probably include search issue.

**Comment by koivunej** [comment]
good to go, squash

**Comment by koivunej** [comment]
pre-squashed with the latest push, good to merge or fast-forward

**Comment by TeroK** [comment]
Can this be changed to be merged into develop instead? I want to avoid master->develop merging and do only develop->master transfers on stable versions.

**Pull request merged**
